# Generated by Django 2.1.5 on 2020-02-01 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='modir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
