# Generated by Django 3.1.dev20200130105839 on 2020-02-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20200202_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('cost', models.FloatField()),
                ('endDate', models.DateField()),
                ('startDate', models.DateField()),
                ('publishDate', models.DateTimeField()),
                ('rejistrationDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('modir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.Modir')),
                ('projecttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.ProjectType')),
            ],
        ),
    ]
