# Generated by Django 2.1.5 on 2020-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20200202_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charity',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='charity',
            name='photo_sanad',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
