# Generated by Django 3.1.dev20200130105839 on 2020-02-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_project_projecttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projecttype',
            new_name='projectType',
        ),
    ]
