# Generated by Django 3.1.dev20200130105839 on 2020-02-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20200202_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rejistrationDate',
            field=models.DateTimeField(),
        ),
    ]
