# Generated by Django 2.1.5 on 2020-02-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20200202_1559'),
        ('charity', '0007_auto_20200203_0237'),
    ]

    operations = [
    ]
