# Generated by Django 2.1.5 on 2020-02-03 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_merge_20200203_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='typee',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='TypePost',
        ),
    ]
