# Generated by Django 2.1.5 on 2020-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_auto_20200203_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publishDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='rejistrationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
