# Generated by Django 2.1.5 on 2020-02-03 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_auto_20200203_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
