# Generated by Django 2.1.5 on 2020-02-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_auto_20200203_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kheiriye',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charity.Charity'),
        ),
    ]
