# Generated by Django 2.1.5 on 2020-02-04 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0018_dastebanamdy_ch_dastebanamdy_ld'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dastebanamdy_LD',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charity.Dastebanamdy_LD'),
        ),
        migrations.AddField(
            model_name='project',
            name='dastebandy_G',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charity.Dastebanamdy_ch'),
        ),
    ]
