# Generated by Django 2.1.5 on 2020-02-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0019_auto_20200204_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCampain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='campain_typ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charity.TypeCampain'),
        ),
    ]
