# Generated by Django 2.1.5 on 2020-02-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0021_auto_20200206_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='charity',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='charity.Charity'),
        ),
    ]
