# Generated by Django 2.1.5 on 2020-02-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0022_project_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='charity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charity.Charity'),
        ),
    ]
