# Generated by Django 2.1.5 on 2020-02-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0024_auto_20200206_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='charity',
        ),
    ]
