# Generated by Django 2.1.5 on 2020-02-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0026_project_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campain_typ',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.TypeCampain'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dastebanamdy_LD',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Dastebanamdy_LD'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dastebandy_G',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Dastebanamdy_ch'),
        ),
    ]
