# Generated by Django 2.1.5 on 2020-02-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_auto_20200206_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='charity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charity.Charity'),
        ),
    ]
