# Generated by Django 3.1.dev20200130105839 on 2020-02-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0028_auto_20200206_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='participateProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.FloatField()),
                ('seSote', models.BooleanField(default=False)),
                ('paidDate', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='userPaid', through='charity.participateProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
